ignore = [
  # I don't care about long lines
  "E501",
]

[isort]
known-first-party = ["sdk_reforge", "reforge_pb2", "reforge_pb2_grpc", "tests"]
force-single-line = true
required-imports = ["from __future__ import annotations"]


[per-file-ignores]
"__init__.py" = ["F401"]
